"""
Diagnostic report model — stores NLP analysis results for a completed chat session.
"""
import uuid

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.chat.models import ChatSession


class DiagnosticReport(models.Model):
    """
    NLP-derived analysis of a completed ChatSession.

    Stores sentiment scores, identified keyword patterns, n-gram frequencies,
    and an overall assessment summary generated by the NLP pipeline.
    """

    class StatusChoices(models.TextChoices):
        PENDING = "pending", "Pending"
        PROCESSING = "processing", "Processing"
        COMPLETED = "completed", "Completed"
        FAILED = "failed", "Failed"

    class SeverityChoices(models.TextChoices):
        NONE = "none", "None / Minimal"
        MILD = "mild", "Mild"
        MODERATE = "moderate", "Moderate"
        SEVERE = "severe", "Severe"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        ChatSession,
        on_delete=models.CASCADE,
        related_name="diagnostic_report",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="diagnostic_reports",
    )
    status = models.CharField(
        max_length=20,
        choices=StatusChoices.choices,
        default=StatusChoices.PENDING,
        db_index=True,
    )

    # -----------------------------------------------------------------------
    # Sentiment analysis
    # -----------------------------------------------------------------------
    overall_sentiment_score = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(-1.0), MaxValueValidator(1.0)],
        help_text="Polarity score in [-1.0 (negative), +1.0 (positive)].",
    )
    sentiment_label = models.CharField(
        max_length=20,
        blank=True,
        help_text="Derived label: 'positive', 'neutral', or 'negative'.",
    )
    subjectivity_score = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],
        help_text="TextBlob subjectivity in [0 (objective), 1 (subjective)].",
    )

    # -----------------------------------------------------------------------
    # Pattern extraction (JSON fields)
    # -----------------------------------------------------------------------
    top_keywords = models.JSONField(
        default=list,
        blank=True,
        help_text="List of {term, score} dicts for the most significant terms.",
    )
    bigrams = models.JSONField(
        default=list,
        blank=True,
        help_text="Most frequent bigrams extracted from user messages.",
    )
    trigrams = models.JSONField(
        default=list,
        blank=True,
        help_text="Most frequent trigrams extracted from user messages.",
    )
    identified_patterns = models.JSONField(
        default=list,
        blank=True,
        help_text="Domain-specific patterns flagged (e.g. 'sleep_issues', 'social_withdrawal').",
    )

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    severity_level = models.CharField(
        max_length=20,
        choices=SeverityChoices.choices,
        default=SeverityChoices.NONE,
    )
    summary = models.TextField(
        blank=True,
        help_text="Human-readable narrative generated from the NLP results.",
    )
    recommendations = models.JSONField(
        default=list,
        blank=True,
        help_text="List of recommended resource tags or action items.",
    )
    error_message = models.TextField(
        blank=True,
        help_text="Populated if status=failed; stores the exception message.",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "diagnostic report"
        verbose_name_plural = "diagnostic reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Report {self.id} — {self.user.email} [{self.status}]"
