// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqV3wJLTosaYHfm_H6__ECoZVHmI6kZ0',
    appId: '1:963022358552:web:109d113860dd11f964db6d',
    messagingSenderId: '963022358552',
    projectId: 'mentallico-efdfc',
    authDomain: 'mentallico-efdfc.firebaseapp.com',
    storageBucket: 'mentallico-efdfc.firebasestorage.app',
    measurementId: 'G-CPZSHG5T0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7oeFmNfxW1LR-FPOOuiYe3rEyr-22x0U',
    appId: '1:963022358552:android:8744d0346850327764db6d',
    messagingSenderId: '963022358552',
    projectId: 'mentallico-efdfc',
    storageBucket: 'mentallico-efdfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoNtQDsgkM6fqMyD6TZ3xsmn6uxnM0X0w',
    appId: '1:963022358552:ios:cfa4a34afe691e1f64db6d',
    messagingSenderId: '963022358552',
    projectId: 'mentallico-efdfc',
    storageBucket: 'mentallico-efdfc.firebasestorage.app',
    iosBundleId: 'com.mentallico.mentallicoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoNtQDsgkM6fqMyD6TZ3xsmn6uxnM0X0w',
    appId: '1:963022358552:ios:cfa4a34afe691e1f64db6d',
    messagingSenderId: '963022358552',
    projectId: 'mentallico-efdfc',
    storageBucket: 'mentallico-efdfc.firebasestorage.app',
    iosBundleId: 'com.mentallico.mentallicoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBqV3wJLTosaYHfm_H6__ECoZVHmI6kZ0',
    appId: '1:963022358552:web:532a7e0ac9d2669364db6d',
    messagingSenderId: '963022358552',
    projectId: 'mentallico-efdfc',
    authDomain: 'mentallico-efdfc.firebaseapp.com',
    storageBucket: 'mentallico-efdfc.firebasestorage.app',
    measurementId: 'G-NM8C48RDQV',
  );
}
