# Generated by Django 5.0.6 on 2026-07-02 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for front-end rendering (e.g. 'brain').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('exercise', 'Exercise / Activity'), ('hotline', 'Crisis Hotline'), ('tool', 'Interactive Tool')], default='article', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('summary', models.TextField(help_text='A short paragraph summarising the resource.')),
                ('body', models.TextField(blank=True, help_text='Full article body (may be empty for external links).')),
                ('external_url', models.URLField(blank=True, help_text='External link if the resource is hosted elsewhere.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Free-form tags used by the recommendation engine (e.g. ['sleep_issues', 'anxiety_indicators']).")),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_crisis_resource', models.BooleanField(db_index=True, default=False, help_text='Flag resources that should surface during a crisis (severity=severe).')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='resources.category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='resources.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved resource',
                'verbose_name_plural': 'saved resources',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'is_crisis_resource'], name='resources_a_is_publ_e0b4ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedresource',
            unique_together={('user', 'article')},
        ),
    ]
