org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=256m
org.gradle.parallel=false
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true


# Unity integration
unity.androidSdkPath=C:/Users/hanee/AppData/Local/Android/Sdk
unity.androidNdkPath=C:/Users/hanee/AppData/Local/Android/Sdk/ndk/27.2.12479018
unity.androidNdkVersion=27.2.12479018
unityStreamingAssets=.html
kotlin.incremental=false
