# Generated by Django 5.0.6 on 2026-07-07 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='User-controlled progress (0-100), adjusted directly via +/- in the UI rather than derived from daily completions.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
