org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=.html
unityTemplateVersion=21
unityProjectPath=F:/Mentallico/Mentallico
unity.projectPath=F:/Mentallico/Mentallico
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=25
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.DefaultCompany.VRTemplate
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=9.2.1
unity.namespace=com.DefaultCompany.VRTemplate
unity.agpVersion=8.10.0
unity.androidSdkPath=C:/Users/hanee/AppData/Local/Android/Sdk
unity.androidNdkPath=C:/Users/hanee/AppData/Local/Android/Sdk/ndk/27.2.12479018
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Java/jdk-18.0.2
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never