# Generated by Django 5.0.6 on 2026-03-27 08:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-defined label for this session.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('analyzed', 'Analyzed')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat session',
                'verbose_name_plural': 'chat sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=10)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Approximate token count for cost / rate-limit accounting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(blank=True, help_text="Overall polarity of the patient's messages in [-1.0, +1.0].", null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sentiment_label', models.CharField(blank=True, help_text="Derived label: 'positive', 'neutral', or 'negative'.", max_length=20)),
                ('disorder_tags', models.JSONField(blank=True, default=list, help_text='List of detected pattern/category labels.')),
                ('severity', models.CharField(choices=[('none', 'None / Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Narrative generated from the NLP results.')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Suggested resource tags or actions for the patient.')),
                ('is_mock', models.BooleanField(default=True, help_text='Set to False once a production NLP model is integrated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_report', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'diagnosis report',
                'verbose_name_plural': 'diagnosis reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
